docs(formulaire) : add description to formulaire module + change imag…
opendigitaleducation/application-help-2d pull request #14
Opened 2023-01-02 08:25 UTC by zoeminondo

2023-01-09 15:09 UTC, sybilleForG commented
Sur ce Commit, pour Formulaire, je vois bien les images qui ont été supprimées et les modifications du .md, mais je ne vois pas les images qui ont été ajoutées et renommées pour remplacer les précédentes.

2023-02-01 08:55 UTC, zoeminondo commented
Ajout des images

2023-02-02 17:18 UTC, sybilleForG requested changes
La plupart des images sont trop larges et seront illisibles sur l'aide en ligne contextuelle. Il faudrait soit recentrer la capture, soit rétrécir au maximum la largeur du navigateur avant capture (à la limite du responsive ou du chevauchement)

2023-02-03 10:57 UTC, zoeminondo commented
Les images ont bien été redimensionnées, je reste disponible si il y a d'autres retours

2023-02-03 16:40 UTC, merged